language: php
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    - anthonys@hexonet.net
    - tseelamkurthi@hexonet.net
    on_success: never
    on_failure: always
php:
- 5.6
- 7.2
- 7.3
# Trigger a push build on master, next and dependabot branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - next
    - /^dependabot.*$/
before_install:
  - export PATH="$HOME/.config/composer/vendor/bin:$PATH"
  - travis_retry wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-1-amd64.deb
  - sudo dpkg -i pandoc-2.6-1-amd64.deb
install:
  - travis_retry composer install
  - travis_retry composer global require squizlabs/php_codesniffer
script:
  - composer run-script test
  - composer run-script codeCheck
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm prune
        - travis_retry npm i
        - npx semantic-release